on: [push, pull_request]

name: Continuous integration

jobs:
  deploy-docker:
    name: Push to DockerHub
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: swiddis/etoast-site:latest

  deploy-vps:
    name: Deploy to VPS
    needs: deploy-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            docker compose pull website
            docker compose up website --detach
